name: release-prod

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-prod:
    uses: ./.github/workflows/build-and-push.yml
    with:
      ecr-role: arn:aws:iam::757190845455:role/git-ops-ecr
