name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-dev:
    uses: ./.github/workflows/build-and-push.yml
    with:
      ecr-role: arn:aws:iam::542218630570:role/git-ops-ecr
  release-prod:
    uses: ./.github/workflows/build-and-push.yml
    with:
      ecr-role: arn:aws:iam::757190845455:role/git-ops-ecr
